### PR TITLE
PluralRule for DualFromZeroToTwo: Does not cover value of 2 - Closes #369

### LINKED ISSUE #369: PluralRule for DualFromZeroToTwo: Does not cover value of 2
### Discussed in https://github.com/axuno/SmartFormat/discussions/363

<div type='discussions-op-text'>

<sup>Originally posted by **Fuitad** December  4, 2023</sup>
Heya,

I'm trying to understand why French is set to DualFromZeroToTwo instead of DualOneOther like English. I'm French Canadian and I'm having a hard time understanding why

``{0:plural:No object|{} object|{} objects} cached on file system`` is working in English but ``{0:plural:Aucun objet|{} objet|{} objets} en cache sur le système`` in French is giving me ``SmartFormat.Core.Formatting.FormattingException: Error parsing format string: Invalid number of plural parameters in PluralLocalizationFormatter``

Maybe there's something in FR-FR that explains this? But on a French Canadian point of view, this doesn't make much sense.</div>

### PR DESCRIPTION
**Pull request by axunonb**
PluralRule for DualFromZeroToTwo: Does not cover value of 2

The `Dictionary<string, PluralRuleDelegate> IsoLangToDelegate` is backed by a default dictionary. It can be restored with `PluralRules.RestoreDefault()` if one of the delegates was changed. Both has global effect.

Extract class `CustomPluralRuleProvider` to its own file

`PluralRuleDelegate DualFromZeroToTwo`:
* with 3 words, the index is for counts of 0, > 0 and < 2, more than 2
* with 4 words, the index is for counts of 0, > 0 and < 2,  >= 2 and < 3, more than 3

Add unit tests

### CODE REVIEW

File: src/SmartFormat/Utilities/PluralRules.cs [hunk 1]
```diff
@@ -217,44 +231,44 @@ public static class PluralRules
...
     {
-        return n switch {
-            0 => 0,
+        return Math.Abs(n) switch
+        {
+            <=0 => 0,
             > 0 and < 2 => 1,
-            > 2 => 2,
-            _ => -1
+            >= 2 => 2
```
Comment (karljj1) [inline src/SmartFormat/Utilities/PluralRules.cs:246]: Maybe this should be the default instead? `_ => 2`

File: src/SmartFormat/Utilities/PluralRules.cs [hunk 2]
```diff
@@ -217,44 +231,44 @@ public static class PluralRules
...
-            0 => 1,
-            > 0 and < 2 => 2,
-            > 2 => 3,
-            _ => -1
+        return Math.Abs(n) switch
+        {
+            <=0 => 0,
+            > 0 and < 2 => 1,
+            >= 2 and < 3 => 2,
+            > 2 => 3
```
Comment (karljj1) [inline src/SmartFormat/Utilities/PluralRules.cs:257]: Should this be `>= 3` instead of `> 2`? or maybe use the default to be safe?
`_ => 3`?

File: src/SmartFormat/Utilities/PluralRules.cs [hunk 3]
```diff
@@ -284,17 +298,20 @@ value switch
...
             ? 0
             : // one
             1;
     private static PluralRuleDelegate Langi => (value, pluralWordsCount) =>
-        value == 0 ? 0 : // zero
-        value is > 0 and < 2 ? 1 : // one
-        2;
+        value switch
+        {
+            0 => 0,
```
Comment (karljj1) [inline src/SmartFormat/Utilities/PluralRules.cs:308]: Do we need to handle negative values?

`<=0 => 0`

**Review by karljj1 — CHANGES_REQUESTED** [review]

File: src/SmartFormat/Utilities/PluralRules.cs (hunk 1 above)
Comment (axunonb) [reply src/SmartFormat/Utilities/PluralRules.cs]: 👍

File: src/SmartFormat/Utilities/PluralRules.cs (hunk 2 above)
Comment (axunonb) [reply src/SmartFormat/Utilities/PluralRules.cs]: 👍

File: src/SmartFormat/Utilities/PluralRules.cs (hunk 3 above)
Comment (axunonb) [reply src/SmartFormat/Utilities/PluralRules.cs:308]: Good point. Throwing for negative values would mean a breaking change.
With other rules, negative values return the maximum index. This is not handled consistently. What do you think?

Comment (karljj1) [reply src/SmartFormat/Utilities/PluralRules.cs:308]: Is there a difference between a negative plural and a positive in any language? Maybe we just need to Abs the value and treat it as positive before we evaluate it?

Comment (axunonb) [reply src/SmartFormat/Utilities/PluralRules.cs:308]: Hm, not 100% sure for each language. As I see it, it's not about the language, but rather about the implementation. The Abs solution you mentioned could be a way to better consistency.

File: src/SmartFormat/Utilities/PluralRules.cs [hunk 4]
```diff
@@ -217,44 +231,44 @@ public static class PluralRules
...
-            > 0 and < 2 => 2,
-            > 2 => 3,
-            _ => -1
+        return Math.Abs(n) switch
+        {
+            <=0 => 0,
+            > 0 and < 2 => 1,
+            >= 2 and < 3 => 2,
+            _ => 3
         };
```
Comment (axunonb) [inline src/SmartFormat/Utilities/PluralRules.cs:258]: @karljj1 While going through the code once again:
[Since the very beginning](https://github.com/axuno/SmartFormat/blob/1f3cd59f43dbbfa2d5e983357d9f1adb9be167b3/src/SmartFormat/Utilities/PluralRules.cs), `PluralRules` are dealing with `decimal`, while comparisons are integer based. As soon as decimal is not an integer, the index for "other" is returned. See also the `Between(...)` method. Can you figure out, what was the intention behind?
If this is the concept, these range comparisons break the concept, don't they?

Comment (karljj1) [reply src/SmartFormat/Utilities/PluralRules.cs:258]: Im not sure I understand. The Between method uses decimals. Maybe Im misunderstanding you?

Comment (axunonb) [reply src/SmartFormat/Utilities/PluralRules.cs:258]: Yes, ` Between` uses decimal, but checks that there is no faction (like 1.0000001). That's what I mean: The comparison there (and in other methods as well) expects that there's no fraction. The range comparison includes fractions and is inconsistent with the other comparisons in this respect, isn't it?
Frankly I don't understand why this kind of implementation was chosen, and I wonder whether there's something I'm just missing.

Comment (karljj1) [reply src/SmartFormat/Utilities/PluralRules.cs:258]: Which range comparison are you referring to that uses fractions?

Comment (axunonb) [reply src/SmartFormat/Utilities/PluralRules.cs:258]: I'm not the author of `PluralRules`, and I think there is an inconsistency. I can't imagine the reason for it.

See these examples:
```C#
// Never include fractional numbers to return true
Assert.That(PluralRules.BetweenWithoutFraction(1.2M, 1M, 2M), Is.False);
Assert.That(PluralRules.BetweenWithoutFraction(1.0M, 1M, 2M), Is.True); // whole number

// Never include fractional numbers
Assert.That(PluralRules.Breton(1M, default), Is.EqualTo(1));
Assert.That(PluralRules.Breton(1.1M, default), Is.EqualTo(5)); // default, not a whole number

// Always include fractional numbers with DualFromZeroToTwo
// Why only here?
Assert.That(PluralRules.GetWordsCount4Value(1M), Is.EqualTo(1));
Assert.That(PluralRules.GetWordsCount4Value(1.1M), Is.EqualTo(1)); // same result for number with fraction
```
What I'm trying to say: Range comparisons for a value are only used with `PluralRules.DualFromZeroToTwo`. This is not consistent or must have a good reason. So what is it?

My guess is, that range comparisons would be the right way for `decimal` (!) values. Why should we use `decimal`, if we compare for equality with whole numbers? Then we could use `long` as well.

Comment (karljj1) [reply src/SmartFormat/Utilities/PluralRules.cs:258]: Yeah, I don't know why it's this way. There is some mention in the CLDR that the _many_ option can also be used for fractions https://cldr.unicode.org/index/cldr-spec/plural-rules

> Fractions
> 
> In some languages, fractions require a separate category. For example, Russian 'other' in the example above. In some languages, they all in a single category with some integers, and in some languages they are in multiple categories. In any case, they also need to be examined to make sure that there are sufficial minimal pairs.
>
> Fractions are often a bit tricky to determine: languages have very different behavior for them. In some languages the fraction is ignored (when selecting the category), in some languages the final digits of the fraction are important, in some languages a number changes category just if there are visible trailing zeros. Make sure to try out a range of fractions to make sure how the numbers behave: values like 1 vs 1.0 may behave differently, as may numbers like 1.1 vs 1.2 vs 1.21, and so on.

Maybe the original used an older version of the CLRD? 

> Fractional support in plurals is new in CLDR 24. Because the fractions didn't work before, the changes in categories from 23 to 24 should not cause an issue for implementations.

Comment (axunonb) [reply src/SmartFormat/Utilities/PluralRules.cs:258]: Thanks a lot, Karl, with your hint to Fraction support the scales fell from my eyes!  ½, 1 ½ sure!
I'll revert to v3.3.0 code, but include 2 as the minimum plural value. Then this is just a bug fix with no breaking changes.

**Review by karljj1 — APPROVED** [review]
